name = "arm_cortex"
description = "arm cortex support (m0, m0p, m4, m4f, m7f, m7df)"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/ohenley/arm_cortex"

authors = ["AdaCore"]
maintainers = ["olivier henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
gnat_arm_elf = "^12"
beta_types = "1.0.0"

[configuration.variables]
core = { type = "Enum", values = ["m0", "m0p", "m4", "m4f", "m7f", "m7df"], default = "m0" }

[origin]
commit = "f128771f84d0995229b52ea759e6506c8eebf6d5"
url = "git+https://github.com/ohenley/arm_cortex.git"

