name = "blinky_stm32f429disco"
description = "Blink leds on the stm32f429disco dev board"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/ohenley/blinky_stm32f429disco"

authors = ["olivier henley"]
maintainers = ["olivier henley <ohenley@gmail.com>"]
maintainers-logins = ["ohenley"]

executables = ["blinky"]

[[depends-on]]
gnat_arm_elf = "^12"
arm_cortex = "1.0.0"
beta_types = "1.0.0"
hal_embedded = "1.0.0"
stm32_svd = "1.0.0"
stm32_drivers = "1.0.0"
stm32_components = "1.0.0"
stm32_boards = "1.0.0"

[configuration.values]
arm_cortex.core = "m4f"
stm32_config.board = "stm32f429disco"
stm32_config.mcu = "stm32f429x"
stm32_config.runtime = "embedded"


[origin]
commit = "9e5b72e5f6bfa68186f569381825510b86db662d"
url = "git+https://github.com/ohenley/blinky_stm32f429disco.git"

