name = "hal_embedded"
description = "Hardware Abstraction Layer (HAL)"
version = "1.0.0"
licenses = "BSD-3-Clause"
tags = ["embedded"]

website = "https://github.com/wolfbiters/hal_embedded"
authors = ["wolf biters"]
maintainers = ["wolf biters <the.wolf.biters@gmail.com>"]
maintainers-logins = ["wolfbiters"]

[[depends-on]]
beta_types = "1.0.0"
[origin]
commit = "49cd956a83f1cababefbed3bb76c5e2a8ee9cf4b"
url = "git+https://github.com/wolfbiters/hal_embedded.git"

