name = "beta_types"
description = "Rudimentary types for embedded"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/wolfbiters/beta_types"

authors = ["wolfbiters"]
maintainers = ["wolfbiters <the.wolf.biters@gmail.com>"]
maintainers-logins = ["wolfbiters"]

[origin]
commit = "ad7308c84e1a98ffe94822decd361b4d977f2ff9"
url = "git+https://github.com/wolfbiters/beta_types.git"

