name = "beta_types"
description = "Rudimentary types for embedded"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/wolfbiters/beta_types"

authors = ["wolfbiters"]
maintainers = ["wolfbiters <the.wolf.biters@gmail.com>"]
maintainers-logins = ["wolfbiters"]

[origin]
commit = "7db32ad596df76ee73ea59427466dce986426a75"
url = "git+https://github.com/wolfbiters/beta_types.git"

