name = "beta_types"
description = "Rudimentary types for embedded"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/ohenley/beta_types"

authors = ["Adacore"]
maintainers = ["olivier henley <ohenley@gmail.com>"]
maintainers-logins = ["ohenley"]

[origin]
commit = "6e27d47603a3514d886103de73b335708b8dc67f"
url = "git+https://github.com/ohenley/beta_types.git"

