authors = ["Stephane Carrez",]
description = "Ada Embedded Network Stack"
licenses = "BSD-3-Clause"
maintainers = ["olivier henley <olivier.henley@gmail.com>",]
maintainers-logins = ["ohenley",]
name = "ada_enet"
tags = ["embedded", "network"]
version = "1.0.0"
website = "https://github.com/ohenley/ada-enet"

[configuration]
auto_gpr_with = true
disabled = false
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

#[configuration.values]
#[configuration.values.arm_cortex]
#core = "m7f"

#[configuration.values.stm32_config]
#board = "stm32f746disco"
#mcu = "stm32f746x"
#runtime = "embedded"

[[depends-on]]
gnat_arm_elf = "^12"
arm_cortex = "1.0.0"
beta_types = "1.0.0"
hal_embedded = "1.0.0"
stm32_boards = "1.0.0"
stm32_components = "1.0.0"
stm32_drivers = "1.0.0"
stm32_svd = "1.0.0"
[origin]
commit = "c5d62e44807a56d5a607a7ac654747cdf99c9cef"
url = "git+https://github.com/ohenley/ada-enet.git"

