name = "stm32_config"
description = "STM32 base config"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/wolfbiters/stm32_config"

authors = ["wolf biters"]
maintainers = ["wolf biters <the.wolf.biters@gmail.com>"]
maintainers-logins = ["wolfbiters"]

[configuration.variables]
mcu = { type = "Enum", values = ["stm32f429x"], default = "stm32f429x" }
board = { type = "Enum", values = ["stm32f4" , "stm32f429disco", "stm32f469disco", "stm32f746disco", "stm32f769disco"], default = "stm32f4" }
runtime = { type = "Enum", values = ["embedded", "light", "light_tasking"], default = "embedded" }
[origin]
commit = "86d9c2f3b94bbb3f9082b6924433f5a27f20b5a4"
url = "git+https://github.com/wolfbiters/stm32_config.git"

